##################################################
# RFNoC Sources
##################################################

RFNOC_SRCS += $(addprefix $(RFNOC_NEURALNET_DIR)/fpga-src/, \
noc_block_ex1layer.v \
)
